# build JSyndicateFS package

# add dnlibs
import dnlibs
import os

# get our environment
Import('env')
env = env.Clone()

# get current path
CurPath = Dir('.').srcnode().abspath + "/"

LibraryPath = "libs"
DependencyFile = CurPath + "dependencies.xml"
LibraryAbsPath = CurPath + LibraryPath

if not (os.path.isdir(LibraryAbsPath) and os.path.exists(LibraryAbsPath)):
   # make dir
   os.mkdir(LibraryAbsPath)

dnlibs.downloadDependencies(DependencyFile, LibraryAbsPath + "/")

Return(  )

