
#Amazon credentials
AWS_ACCESS_KEY_ID = 'XXX'
AWS_SECRET_ACCESS_KEY = 'XXX'

#Google credentials
GOOGLE_CLIENT_ID = 'XXX'
GOOGLE_CLIENT_SECRET = 'XXX'
GOOGLE_REDIRECT_URL = 'XXX'

#Dropbox credentials
DROPBOX_APP_KEY = 'XXX'
DROPBOX_APP_SECRET = 'XXX'
DROPBOX_ACCESS_TOKEN = 'XXX'