"""
   Copyright 2013 The Trustees of Princeton University

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""

# build libAGdiskpollingdriver.so

import os

# add additional source files here
source_files = """
   driver.cpp
   directory_monitor.cpp
   timeout_event.cpp
"""

# add source file search paths here
CPPPATH = """
   #libsyndicate/
   #build/out/protobufs
   #AG/drivers/common
"""

# add library paths here
LIBPATH = """
   #build/out/libsyndicate
"""

# add libraries here
LIBS = """
   AGcommon
   syndicate
   pthread
"""

# add additional CPPFLAGS here
CPPFLAGS = ""


# get our environment
Import('env')
env = env.Clone()

env.Append(LIBS = Split(LIBS))
env.Append(CPPPATH = Split(CPPPATH))
env.Append(CPPFLAGS = CPPFLAGS)
env.Append(LIBPATH = Split(LIBPATH))
env.Append(LINKFLAGS = ['-Wl,--export-dynamic'])

# generate the shared library
libAGdiskpollingdriver = env.SharedLibrary( target="libAGdiskpollingdriver.so", source=[Split(source_files)] )

Return( 'libAGdiskpollingdriver' )
