#!/bin/sh

#   Copyright 2013 The Trustees of Princeton University
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

DESC="Syndicate automount daemon"
NAME="syndicated.py"

SYNDICATED=/usr/bin/syndicated.py
#SYNDICATED="./syndicated.py -s 0123456789abcdef"

CONFIG=/etc/syndicated/syndicated.conf 
#CONFIG=./opencloud/syndicated.conf

SLICENAME="test2"

start() {
   $SYNDICATED -c $CONFIG -S $SLICENAME
}

stop() {
   $SYNDICATED -c $CONFIG -S $SLICENAME stop
}

restart() {
   stop
   start
}

status() {
   $SYNDICATED -c $CONFIG -S $SLICENAME status
}

case "$1" in
   start)
      echo -n "Starting $DESC:  "
      start
      if [ $? -ne 0 ]; then
         echo "FAILED"
      else
         echo "$NAME"
      fi
      ;;

   stop)
      echo -n "Stopping $DESC:  "
      stop
      if [ $? -ne 0 ]; then
         echo "FAILED"
      else
         echo "$NAME"
      fi
      ;;

   restart)
      echo -n "Restarting $DESC:  "
      restart 
      if [ $? -ne 0 ]; then
         echo "FAILED"
      else
         echo "$NAME"
      fi
      ;;

   status)
      status; exit $?
      ;;

   *)
      echo "Usage: $NAME {start|stop|restart|status}" >&2
      exit 1
      ;;

esac

exit 0
