"""
   Copyright 2013 The Trustees of Princeton University

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""


import os

Import('env')
env = env.Clone()

# get a list of opencloud-specific files 
target_config = env.Command( "etc/syndicated/syndicated.conf", "syndicated.conf", Move("$TARGET", "$SOURCE") )
target_initscript = env.Command( "etc/init.d/syndicated", "initscript", Move("$TARGET", "$SOURCE") )
target_credserver_pubkey = env.Command( "etc/syndicated/cred-server.pub", "cred-server.pub", Move("$TARGET", "$SOURCE") )
target_cron_update = env.Command( "etc/cron.daily/syndicate-update.sh", "syndicate-update.sh", Move("$TARGET", "$SOURCE") )

targets = [target_config, target_initscript, target_credserver_pubkey, target_cron_update]

env.AlwaysBuild( targets )

Return( 'targets' )
