#!/usr/bin/python
"""
   Copyright 2015 The Trustees of Princeton University

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""

"""
Usage:  fetch_syndicate_pubkey [ms_url]
"""

import os
import sys
import requests 
import traceback 

import syndicate.protobufs.ms_pb2 as ms_pb2
import syndicate.protobufs.sg_pb2 as sg_pb2


MAX_PUBKEY_LEN = 10 * 1024

def print_error( s ):
   print >> sys.stderr, s
   

def fetch_syndicate_pubkey( ms_url ):
   """
   Go fetch the Syndicate public key
   Return the PEM-encoded public key on success
   Return None on error.
   """
   
   pubkey_url = ms_url + "/PUBKEY"
   
   req = requests.get( pubkey_url, stream=True )
   if req.status_code != 200:
      
      req.close()
      print_error("Failed to fetch Syndicate public key from '%s': status code %s" % (pubkey_url, req.status_code))
      return None 
   
   if int(req.headers['content-length']) > MAX_PUBKEY_LEN:
      
      req.close()
      print_error("Public key from '%s' is too long (%s bytes)" % (pubkey_url, req.headers['content-length']))
      return None
   
   pubkey_text = req.content.strip("\r\n")
   return pubkey_text
   
   
def usage( progname ):
   print "Usage: %s [MS url]" % progname

   
if __name__ == "__main__":
   
   if len(sys.argv) < 2:
      usage( sys.argv[0] )
      sys.exit(1)
      
   ms_url = sys.argv[1]
      
   syndicate_pubkey = fetch_syndicate_pubkey( ms_url )
   if syndicate_pubkey is None:
      sys.exit(1)
   
   else:
      sys.stdout.write( syndicate_pubkey )
      sys.exit(0)