#!/usr/bin/python
"""
   Copyright 2015 The Trustees of Princeton University

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""

"""
Usage: validate_user_cert < ms_user_cert

Reads an ms_user_cert from stdin, and exits 0 if it is valid, or exits 1 if not.
"""


import os
import sys
import requests 
import traceback 

import syndicate.protobufs.ms_pb2 as ms_pb2
import syndicate.protobufs.sg_pb2 as sg_pb2

if __name__ == "__main__":
   
   protobuf_str = sys.stdin.read()
   user_cert = None
   
   try:
      user_cert = ms_pb2.ms_user_cert()
      user_cert.ParseFromString( protobuf_str )
   except Exception, e:
      traceback.print_exc()
      print >> sys.stderr, "Failed to parse user cert"
      sys.exit(1)
   
   # no-op for testing 
   sys.exit(0)