# build libAGdiskdriver.so

import os

# add additional source files here
source_files = """
   driver.cpp
"""

# add source file search paths here
CPPPATH = """
   #libsyndicate/
   #build/out/protobufs
"""

# add library paths here
LIBPATH = """
   #build/out/libsyndicate
"""

# add libraries here
LIBS = """
   syndicate
"""

# add additional CPPFLAGS here
CPPFLAGS = ""


# get our environment
Import('env')
env = env.Clone()

env.Append(LIBS = Split(LIBS))
env.Append(CPPPATH = Split(CPPPATH))
env.Append(CPPFLAGS = CPPFLAGS)
env.Append(LIBPATH = Split(LIBPATH))

# generate the shared library
libAGdiskdriver = env.SharedLibrary( target="libAGdiskdriver.so", source=[Split(source_files)] )

Return( 'libAGdiskdriver' )
