#!/usr/bin/pyhon

"""
   Copyright 2013 The Trustees of Princeton University
   All Rights Reserved
"""

import os

# configuration parameters


# OpenID
OPENID_SESSION_SSL_ONLY=True
OPENID_LOCAL_TEST=True
OPENID_TRUST_ROOT_HOST = ""
OPENID_HOST_URL = ""

if os.environ.get('SERVER_SOFTWARE','').startswith('Development'):
   OPENID_TRUST_ROOT_HOST = "localhost:8080"
   OPENID_HOST_URL = "http://" + OPENID_TRUST_ROOT_HOST
   OPENID_SESSION_SSL_ONLY=False
   OPENID_LOCAL_TEST=True
else:
   OPENID_TRUST_ROOT_HOST = "syndicate-metadata.appspot.com"
   OPENID_HOST_URL = "https://" + OPENID_TRUST_ROOT_HOST
   OPENID_SESSION_SSL_ONLY=True
   OPENID_LOCAL_TEST=False
   
   """
OPENID_PROVIDER_NAME = "VICCI"
OPENID_PROVIDER_URL = "https://www.vicci.org/id/"
OPENID_PROVIDER_AUTH_HANDLER = "https://www.vicci.org/id-allow"
OPENID_PROVIDER_EXTRA_ARGS = {"yes": "yes"}
OPENID_PROVIDER_USERNAME_FIELD = "login_as"
OPENID_PROVIDER_PASSWORD_FIELD = "password"
OPENID_PROVIDER_CHALLENGE_METHOD = "POST"
OPENID_PROVIDER_RESPONSE_METHOD = "POST"
"""

OPENID_PROVIDER_NAME = "localhost"
OPENID_PROVIDER_URL = "http://localhost:8081/id/"
OPENID_PROVIDER_AUTH_HANDLER = "http://localhost:8081/allow"
OPENID_PROVIDER_EXTRA_ARGS = {"yes": "yes"}
OPENID_PROVIDER_USERNAME_FIELD = "login_as"
OPENID_PROVIDER_PASSWORD_FIELD = "password"
OPENID_PROVIDER_CHALLENGE_METHOD = "POST"
OPENID_PROVIDER_RESPONSE_METHOD = "POST"


# gateways
GATEWAY_PASSWORD_LENGTH = 256
GATEWAY_SALT_LENGTH = 256
GATEWAY_SESSION_PASSWORD_LENGTH = 16
GATEWAY_RSA_KEYSIZE = 4096

# volumes
VOLUME_SECRET_LENGTH = 256
VOLUME_SECRET_SALT_LENGTH = 256

VOLUME_RSA_KEYSIZE = 4096

# website
MS_HOST = OPENID_TRUST_ROOT_HOST
MS_URL = OPENID_HOST_URL
