# build libsyndicate python wrapper

# get our environment
Import('env')
env = env.Clone()

source_files = """
   syndicate.pxd
   syndicate.pyx
   setup.py
   __init__.py
"""

# command to build Python wrapper for libsyndicate
libsyndicate_python = env.Command( "syndicate.so", Split(source_files), "cd %s && python ./setup.py build_ext --inplace" % Dir(".").path )

build_files = Glob("*.py")
build_files.append(Glob("*.pxd"))
build_files.append(Glob("*.pyx"))

build_targets = [libsyndicate_python, build_files]

Return( 'build_targets' )
