# build libAGSQLdriver.so

import os

# add additional source files here
source_files = """
   odbc-handler.cpp
   driver.cpp
   map-parser.cpp
"""

# add source file search paths here
CPPPATH = """
   #libsyndicate/
   #build/out/protobufs
"""

# add library paths here
LIBPATH = """
   #build/out/libsyndicate
"""

# add libraries here
LIBS = """
   syndicate
   xerces-c
   odbc
"""

# add additional CPPFLAGS here
CPPFLAGS = "-g"


# get our environment
Import('env')
env = env.Clone()

env.Append(LIBS = Split(LIBS))
env.Append(CPPPATH = Split(CPPPATH))
env.Append(CPPFLAGS = CPPFLAGS)
env.Append(LIBPATH = Split(LIBPATH))
env.Append(LINKFLAGS = ['-Wl,--export-dynamic'])

# generate the shared library
libAGSQLdriver = env.SharedLibrary( target="libAGSQLdriver.so", source=[Split(source_files)] )

Return( 'libAGSQLdriver' )

