/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ag_daemon_CONSTANTS_H
#define ag_daemon_CONSTANTS_H

#include "ag_daemon_types.h"

namespace watchdog {

class ag_daemonConstants {
 public:
  ag_daemonConstants();

};

extern const ag_daemonConstants g_ag_daemon_constants;

} // namespace

#endif
