/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ag_daemon_constants.h"

namespace watchdog {

const ag_daemonConstants g_ag_daemon_constants;

ag_daemonConstants::ag_daemonConstants() {
}

} // namespace

