// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "AGDaemon_server.h"


AGDaemonHandler::AGDaemonHandler() {
    // Your initialization goes here
    asi = new AGDaemon_service_impl();
}

int32_t AGDaemonHandler::restart(const int32_t ag_id) {
    // Your implementation goes here
    printf("restart\n");
    return 0;
}

void AGDaemonHandler::ping( ::watchdog::PingResponse& _return) {
    // Your implementation goes here
    printf("ping\n");
    PingResponse_local prl = asi->ping();
    _return.id = prl.id;
    _return.dead_set = prl.dead_set;
    _return.live_set = prl.live_set;
}

