/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "common_constants.h"

namespace watchdog {

const commonConstants g_common_constants;

commonConstants::commonConstants() {
}

} // namespace

