/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef wd_daemon_CONSTANTS_H
#define wd_daemon_CONSTANTS_H

#include "wd_daemon_types.h"

namespace watchdog {

class wd_daemonConstants {
 public:
  wd_daemonConstants();

};

extern const wd_daemonConstants g_wd_daemon_constants;

} // namespace

#endif
