/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "wd_daemon_constants.h"

namespace watchdog {

const wd_daemonConstants g_wd_daemon_constants;

wd_daemonConstants::wd_daemonConstants() {
}

} // namespace

