"""
   Copyright 2013 The Trustees of Princeton University

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""

# get our environment
Import('env')
Import("nacl_env")
Import("extra_args")

# sanity check
if nacl_env is None:
   target = None
   Return( "target" )

Import("fs_objs_nacl")
Import("syndicate_common_objs_nacl")

# add additional source files here
source_files = """
   client.cpp
   nacl_main.cpp
"""

# add source file search paths here
CPPPATH = """
   #UG/
   #UG/fs/
   #libsyndicate/
   #build/out/protobufs/
"""

# add library paths here
LIBPATH = """
"""

# add libraries here
LIBS = """
   syndicate_nacl
   ssl
   crypto
   protobuf
   curl
   pthread
   m
   rt
   ppapi
   ppapi_cpp
   nacl_io
   dl
"""

# add additional CPPFLAGS here
CPPFLAGS = ""

# add additional CPPDEFINES here
CPPDEFINES = [
   ("_FILE_OFFSET_BITS", 64),
   "_REENTRANT",
   "_THREAD_SAFE"
]


src = Split(source_files)

nacl_plugin = None

# Native Client plugin
env_nacl = nacl_env.Clone()
env_nacl.Append(LIBS = Split(LIBS))
env_nacl.Append(CPPPATH = Split(CPPPATH))
env_nacl.Append(CPPFLAGS = Split(CPPFLAGS))
env_nacl.Append(CPPDEFINES = CPPDEFINES)

nacl_objs = [env_nacl.Object("%s.nacl.o" % x, x) for x in src]

nacl_plugin = env_nacl.Program( "UG.nexe", nacl_objs + syndicate_common_objs_nacl + fs_objs_nacl )

Return( 'nacl_plugin' )


