"""
   Copyright 2013 The Trustees of Princeton University

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""


# add additional source files here
source_files = """
   close.cpp
   closedir.cpp
   fs_entry.cpp
   link.cpp
   manifest.cpp
   mkdir.cpp
   open.cpp
   opendir.cpp
   read.cpp
   readdir.cpp
   recover.cpp
   rename.cpp
   rmdir.cpp
   stat.cpp
   sync.cpp
   trunc.cpp
   unlink.cpp
   url.cpp
   write.cpp
   xattr.cpp
"""

# add source file search paths here
CPPPATH = """
   #UG/
   #libsyndicate/
   #build/out/protobufs/
"""

# add library paths here
LIBPATH = """
"""

# add libraries here
LIBS = """
"""

# add additional CPPFLAGS here
CPPFLAGS = ""

# add additional CPPDEFINES here
CPPDEFINES = [
   ("_FILE_OFFSET_BITS", 64),
   "_REENTRANT",
   "_THREAD_SAFE"
]

# get our environment
Import('env')
Import("nacl_env")
Import("extra_args")

env = env.Clone()

env.Append(LIBS = Split(LIBS))
env.Append(CPPPATH = Split(CPPPATH))
env.Append(CPPFLAGS = Split(CPPFLAGS))
env.Append(CPPDEFINES = CPPDEFINES)

fs_src = Split(source_files)
fs_objs = [env.Object( "%s.o" % x, x ) for x in fs_src]
fs_sobjs = [env.SharedObject( "%s.so" % x, x ) for x in fs_src]

fs_nacl_objs = None

if nacl_env is not None:
   # Native Client library
   nacl_env = nacl_env.Clone()
   nacl_env.Append(CPPPATH = Split(CPPPATH))

   fs_nacl_objs = [nacl_env.Object("%s.nacl.o" % x, x ) for x in fs_src]

Return( 'fs_objs fs_sobjs fs_nacl_objs' )


