# build libsyndicate python wrapper

# get our environment
Import('env')
env = env.Clone()

import os

build_cmd = "cd %s && rm -rf build/ && python ./setup.py --source-root=%s --build-dir=%s build && cp -a build/lib*/syndicate/* syndicate/" % (Dir(".").path, Dir("#").abspath, os.path.dirname(Dir(".").path))

build_target = env.Command("PYTHON", [], build_cmd )
install_target = env.Command("PYTHON-INSTALL", [], "cd %s && python ./setup.py --source-root=%s --build-dir=%s install" )

env.AlwaysBuild(build_target)

source_files = Glob("syndicate.*")
source_files.extend( Glob("syn.*") )
source_files.extend( Glob("syndicate/*") )
source_files.extend( Glob("setup.py") )

Return("build_target install_target source_files")
