"""
   Copyright 2013 The Trustees of Princeton University

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""

# build libsyndicate python wrapper

# get our environment
Import('env')
Import('extra_args')

env = env.Clone()

import os

distro = "UNKNOWN"

if extra_args.has_key("DISTRO"):
   distro = extra_args["DISTRO"]

build_cmd = "cd %s && rm -rf build/ && python ./setup.py --source-root=%s --build-dir=%s --distro=%s build && cp -a build/lib*/syndicate/* syndicate/" % (Dir(".").path, Dir("#").abspath, os.path.dirname(Dir(".").path), distro)

build_target = env.Command("PYTHON", [], build_cmd )
install_target = env.Command("PYTHON-INSTALL", [], "cd %s && python ./setup.py --source-root=%s --build-dir=%s --distro=%s install --prefix=%s" % (Dir(".").path, Dir("#").abspath, os.path.dirname(Dir(".").path), env['install_prefix'], distro))

env.AlwaysBuild(build_target)

source_files = Glob("syndicate.p*")
source_files.extend( Glob("volume.p*") )
source_files.extend( Glob("syndicate/*.py") )
source_files.extend( Glob("setup.py") )

Return("build_target install_target source_files")
