/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef common_TYPES_H
#define common_TYPES_H

#include <Thrift.h>
#include <TApplicationException.h>
#include <protocol/TProtocol.h>
#include <transport/TTransport.h>



namespace watchdog {

typedef struct _AGDaemonID__isset {
  _AGDaemonID__isset() : addr(false), port(false), frequency(false) {}
  bool addr;
  bool port;
  bool frequency;
} _AGDaemonID__isset;

class AGDaemonID {
 public:

  static const char* ascii_fingerprint; // = "F3540C99C9016F618854ABDC57D34F96";
  static const uint8_t binary_fingerprint[16]; // = {0xF3,0x54,0x0C,0x99,0xC9,0x01,0x6F,0x61,0x88,0x54,0xAB,0xDC,0x57,0xD3,0x4F,0x96};

  AGDaemonID() : addr(""), port(0), frequency(0) {
  }

  virtual ~AGDaemonID() throw() {}

  std::string addr;
  int32_t port;
  int16_t frequency;

  _AGDaemonID__isset __isset;

  void __set_addr(const std::string& val) {
    addr = val;
  }

  void __set_port(const int32_t val) {
    port = val;
  }

  void __set_frequency(const int16_t val) {
    frequency = val;
  }

  bool operator == (const AGDaemonID & rhs) const
  {
    if (!(addr == rhs.addr))
      return false;
    if (!(port == rhs.port))
      return false;
    if (!(frequency == rhs.frequency))
      return false;
    return true;
  }
  bool operator != (const AGDaemonID &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const AGDaemonID & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

} // namespace

#endif
